from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .......models.bad_response_view import BadResponseView
    from .......models.registration_act_article_name_view import RegistrationActArticleNameView
    from .historicalrecord.historicalrecord_request_builder import HistoricalrecordRequestBuilder

class ActArticleNamesRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/publicregister/{languageCode-id}/{registerCode}/Registrations/ActArticleNames
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ActArticleNamesRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/publicregister/{languageCode%2Did}/{registerCode}/Registrations/ActArticleNames", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[list[RegistrationActArticleNameView]]:
        """
        Gets distinct act article names for all registrations for the specified register.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[list[RegistrationActArticleNameView]]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .......models.bad_response_view import BadResponseView

        error_mapping: dict[str, type[ParsableFactory]] = {
            "400": BadResponseView,
            "404": BadResponseView,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .......models.registration_act_article_name_view import RegistrationActArticleNameView

        return await self.request_adapter.send_collection_async(request_info, RegistrationActArticleNameView, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Gets distinct act article names for all registrations for the specified register.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> ActArticleNamesRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ActArticleNamesRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ActArticleNamesRequestBuilder(self.request_adapter, raw_url)
    
    @property
    def historicalrecord(self) -> HistoricalrecordRequestBuilder:
        """
        The historicalrecord property
        """
        from .historicalrecord.historicalrecord_request_builder import HistoricalrecordRequestBuilder

        return HistoricalrecordRequestBuilder(self.request_adapter, self.path_parameters)
    
    @dataclass
    class ActArticleNamesRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

